from __future__ import annotations

import hashlib
import tempfile
import unittest
from pathlib import Path

from virtualauto.evidence import record_evidence


class EvidenceTests(unittest.TestCase):
    def test_records_retained_artifact_without_manual_hashing(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            artifact = root / "lab/evidence/runs/EXP-TEST-001/result.txt"
            artifact.parent.mkdir(parents=True)
            artifact.write_bytes(b"controlled-result")
            record = record_evidence(
                artifact=artifact,
                evidence_id="EVD-TEST-RESULT-001",
                experiment_id="EXP-TEST-001",
                artifact_type="log",
                provenance="Generated by a controlled unit test.",
                rights_status="original",
                root=root,
            )
            self.assertEqual(
                record["sha256"], hashlib.sha256(artifact.read_bytes()).hexdigest()
            )
            self.assertEqual(
                record["repository_path"],
                "lab/evidence/runs/EXP-TEST-001/result.txt",
            )
            self.assertTrue(
                (root / "lab/evidence/records/EVD-TEST-RESULT-001.json").is_file()
            )

    def test_rejects_private_or_external_artifact_paths(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            artifact = root / "private/source.bin"
            artifact.parent.mkdir(parents=True)
            artifact.write_bytes(b"private")
            with self.assertRaisesRegex(ValueError, "lab/evidence"):
                record_evidence(
                    artifact=artifact,
                    evidence_id="EVD-TEST-RESULT-002",
                    experiment_id=None,
                    artifact_type="other",
                    provenance="Generated by a controlled unit test.",
                    rights_status="original",
                    root=root,
                )


if __name__ == "__main__":
    unittest.main()
